#!/usr/bin/env bash

set -e

export -n CDPATH

if [ "$1" = "--debug" ]; then
  export DEVMAC_DEBUG=1
  shift
fi

if [ -n "$DEVMAC_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${DEVMAC_ROOT}" ]; then
  DEVMAC_ROOT="${HOME}/.devmac"
else
  DEVMAC_ROOT="${DEVMAC_ROOT%/}"
fi
export DEVMAC_ROOT

if [ -z "${DEVMAC_DIR}" ]; then
  DEVMAC_DIR="$(pwd)"
else
  cd "$DEVMAC_DIR" 2>/dev/null || {
    echo "devmac: cannot change working directory to \`$DEVMAC_DIR'"
    exit 1
  } >&2
  DEVMAC_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export DEVMAC_DIR

shopt -s nullglob

bin_path="$(abs_dirname "$0")"
export PATH="${bin_path}:${PATH}"

shopt -u nullglob

command="$1"
if [[ "$2" = "--help"  || "$2" = "-h"  ]]; then
  devmac-help "$command" >&2
  exit 1
fi

case "$command" in
"" | "-h" | "--help" )
  echo -e "$(devmac-help)" >&2
  ;;
"-v" )
  exec devmac---version
  ;;
* )
  command_path="$(command -v "devmac-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "devmac: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
